# Generated by Django 5.1.4 on 2024-12-28 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('land', '0001_initial'),
        ('transaction', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='land',
            name='transactions',
            field=models.ManyToManyField(blank=True, related_name='land_transactions', to='transaction.transaction'),
        ),
    ]
